#ifndef GUARD_CONSTANTS_NEW_STATES_H
#define GUARD_CONSTANTS_NEW_STATES_H

// Cutscene States
    // Intro: VAR_INTRO_CUTSCENE_STATE
    #define INTRO_CUTSCENE_STATE_0 0

// Town/City States
    // Woodridge: VAR_WOODRIDGE_TOWN_STATE
    #define WOODRIDGE_STATE_CLOCK_SET 1
    #define WOODRIDGE_STATE_CALLED_PARENTS 2
    #define WOODRIDGE_STATE_POST_VWT_SUBZERO_ENCOUNTER 3
    #define WOODRIDGE_STATE_ADVENTURE_BEGIN 4
    
    // Animora: VAR_ANIMORA_CITY_STATE
    #define ANIMORA_STATE_RECEIVED_DEX 1
    #define ANIMORA_STATE_COMPLETED_CATCH_TUTORIAL 2
    #define ANIMORA_STATE_ADVENTURE_BEGIN 3

    // Centra (General): VAR_CENTRA_CITY_STATE
    //#define CENTRA_STATE_WATCHED_SUBZERO_CUTSCENE 1
    //#define CENTRA_STATE_HARLEY_INTRODUCED 2
    
    // Centra (Southwest): VAR_CENTRA_SW_STATE
    #define CENTRA_SW_STATE_RECEIVED_LETTER_DEXNAV 1

    // Olstern: VAR_OLSTERN_CITY_STATE
    #define OLSTERN_STATE_TAMMY_ENCOUNTER_START 1
    #define OLSTERN_STATE_TAMMY_ENCOUNTER_END 2
    #define OLSTERN_STATE_GYM_DEFEATED 3
    #define OLSTERN_STATE_EXPLOSION_HEARD 4
    #define OLSTERN_STATE_HEALED_AFTER_GYM_BATTLE 21
    #define OLSTERN_STATE_KIDNAPPED 22

// Route States
    // Vast Woods Trail: VAR_VAST_WOODS_TRAIL_STATE
    #define VWT_STATE_HEARD_MON_CRIES 1
    #define VWT_STATE_CHOOSING_STARTER 2
    #define VWT_STATE_SUBZERO_BATTLE 3
    #define VWT_STATE_POST_BATTLE 4
    
    // Route 1: VAR_ROUTE1_STATE
    #define R1_STATE_NO_ENTRY 0
    #define R1_STATE_ENTRY_ALLOWED 1
    #define R1_STATE_SCRIPTED_WILD_MON 2
    #define R1_STATE_CATCH_TUTORIAL 3
    #define R1_STATE_COMPLETED_CATCH_TUT 4
    
    // Route 3: VAR_ROUTE3_STATE
    #define R3_STATE_HARLEY_DEFEATED 1

    // Route 4: VAR_ROUTE4_STATE
    #define R4_STATE_REACHED_HALFWAY 1

// Gym States
    // Aria: VAR_CENTRA_SE_GYM_STATE
    #define CENTRA_SE_GYM_STATE_CHALLENGE_STARTED 1
    #define CENTRA_SE_GYM_STATE_DEFEATED 2

    // Redbeard: VAR_OLSTERN_GYM_STATE
    #define OLSTERN_GYM_STATE_CHALLENGE_STARTED 1
    #define OLSTERN_GYM_STATE_CHALLENGE_COMPLETE 2
    #define OLSTERN_GYM_STATE_DEFEATED 3
    #define OLSTERN_GYM_STATE_EMERGE_DEFEATED 4
    #define OLSTERN_GYM_STATE_EMERGE_CHALLENGE_STARTED 5
    #define OLSTERN_GYM_STATE_EMERGE_CHALLENGE_COMPLETE 6

    // Laurent: VAR_CENTRA_NW_GYM_STATE
    #define CENTRA_NW_GYM_STATE_CHALLENGE_STARTED 1

// Dungeon States
    // Vast Woods: VAR_VAST_WOODS_STATE
    #define VAST_WOODS_STATE_SUBZERO_HIDEOUT_CUTSCENE 0

    // Unnamed Cave: VAR_UMN_CAVE_STATE
    #define UMN_CAVE_STATE_CAVE_IN_CLEARED 1
    
    // Old Ironworks: VAR_NEW_MAUVILLE_STATE
    #define IRONWORKS_STATE_SUBZERO_DEFEATED 1

// Weather Slots for EventScript_RandomWeather
#define WEATHER_SET_DEFAULT      1 // Clear, Rain
#define WEATHER_SET_DEFAULT_PLUS 2 // Clear, Rain, Thunderstorm, Shade
#define WEATHER_SET_RAIN_ONLY    3 // Rain only
#define WEATHER_SET_RAIN_PLUS    4 // Rain, Thunderstorm, Shade
#define WEATHER_SET_SNOW_CYCLE   5 // Clear, Snow
#define WEATHER_SET_SNOW_ONLY    6 // Self-explanatory
#define WEATHER_SET_ANY         32 // Clear, Rain, Thunderstorm, Drought/Fog, Shade, Snow


#endif  // GUARD_CONSTANTS_NEW_STATES_H
